[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  # Secrets removed from version control. Configure on the platform instead.

# API redirects to Netlify functions
[[redirects]]
  from = "/api/liteapi/*"
  to = "/.netlify/functions/liteapi-proxy"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/liteapi-proxy"
  status = 200

# SPA redirect - must be last rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
