# CI/CD Bundle Monitoring GitHub Action

name: Bundle Size Monitor

# Make this workflow optional - don't block other workflows
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

# Cancel previous runs
concurrency:
  group: bundle-monitor-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true # Don't fail the entire workflow if this fails
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetch history for comparison
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
    
    - name: Download bundle history
      uses: actions/cache/restore@v3
      with:
        path: bundle-history.json
        key: bundle-history-${{ github.repository }}-${{ github.ref }}
        restore-keys: |
          bundle-history-${{ github.repository }}-
    
    - name: Build project for analysis
      run: |
        echo "Building project for bundle analysis..."
        npm run build || npm run build:safe || echo "Build failed, will analyze existing build if available"
      env:
        NODE_OPTIONS: '--max-old-space-size=6144'
        CI: true
    
    - name: Run bundle size analysis
      run: |
        echo "Starting bundle analysis..."
        SKIP_BUILD=true node scripts/bundle-monitor.js analyze || {
          echo "Bundle analysis failed, but continuing..."
          echo "This is not a critical failure."
          exit 0
        }
      env:
        CI: true
        SKIP_BUILD: true
    
    - name: Upload bundle analysis report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bundle-analysis-report
        path: |
          dist/
          bundle-history.json
        retention-days: 30
    
    - name: Save bundle history
      uses: actions/cache/save@v3
      if: always()
      with:
        path: bundle-history.json
        key: bundle-history-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
    
    - name: Comment PR with bundle analysis
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          // Run bundle analysis and capture output
          let output = '';
          try {
            output = execSync('node scripts/bundle-monitor.js analyze', { encoding: 'utf8' });
          } catch (error) {
            output = error.stdout + error.stderr;
          }
          
          // Create comment body
          const commentBody = `
          ## 📊 Bundle Size Analysis
          
          \`\`\`
          ${output}
          \`\`\`
          
          <details>
          <summary>📈 View Historical Trends</summary>
          
          Run \`npm run bundle:history\` locally to see detailed trends.
          
          </details>
          `;
          
          // Find existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const existingComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Bundle Size Analysis')
          );
          
          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
          }

  # Simplified bundle comparison - disabled for now to avoid complexity
  # bundle-comparison:
  #   runs-on: ubuntu-latest
  #   if: false # Disabled until we optimize this further
  #   timeout-minutes: 15
  #   continue-on-error: true
